data_source:
  type: csv
  path: data/raw/heart-disease.csv

target_column: "target"

model_params:
  model_type: RandomForest
  params:
    n_estimators: 100
    max_depth: 5

mlflow_config:
  experiment_name: "generic_ml_project"
  tracking_uri: "file:./experiments/mlruns"
